### ISSUE TITLE
HVV API Contract

### ISSUE THREAD

**Issue by Fexxel** [georg90/MMM-HH-LocalTransport#2]
Hi Georg,

thanks for sharing your plugin! This is exactly what I was looking for.
Regarding the API Contract with the HVV: Are you using the "test phase" only or did you migrate to the "production phase"?

**Comment by georg90** [comment]
I'm honestly not sure on which server I am right now :) I think when they roll out the production phase, it will be available without signing up etc.

It's still working fine, except it sometimes "hangs" - one thing I need to improve.

**Comment by georg90** [comment]
closing this for #7
